### ISSUE TITLE
Add support for webhooks

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce-mollie#13] opened 2019-02-26 12:21 UTC
Somehow, in a newer install of this plugin, the webhook url doesn't get sent to Mollie, as it did previously. I think you only need to add the `supportsWebhooks` method to the gateway, returning true. Please do this for the feature/issuers version to, as that's the one we always use (when will this be merged into master?).

**Comment by andris-sevcenko** [comment] 2019-02-26 13:24
This is probably due to that link being sent out when it shouldn't have been (craftcms/commerce-omnipay@44ec14e885a0c21acd2d0d9b3501f0cdd4b0f886).

I'll fix this and I plan to get a release for all omnipay gateways this week.

**Comment by nilsenpaul** [comment] 2019-02-26 13:36
@andris-sevcenko you're my hero.

**Comment by andris-sevcenko** [comment] 2019-02-28 13:50
Closed via a32ba5b

**Closed by andris-sevcenko** 2019-02-28 13:50 UTC

**Comment by nilsenpaul** [comment] 2019-03-01 10:20
@andris-sevcenko When I use the v2.x-dev versions for both commerce-mollie and commerce-ominpay, I get the following webhook error:

`Exception while processing webhook: Return value of craft\commerce\omnipay\base\Gateway::processWebHook() must be an instance of craft\web\Response, null returned`

`Exception thrown in /var/www/.../vendor/craftcms/commerce-omnipay/src/base/Gateway.php:349`

**Comment by nilsenpaul** [comment] 2019-03-01 10:24
@andris-sevcenko Sorry, I almost forgot that it's World Compliment Day. You're doing a great job, keep up the good work!

**Comment by andris-sevcenko** [comment] 2019-03-01 10:44
@nilsenpaul load up Discord, let's chat!

**Comment by nilsenpaul** [comment] 2019-03-01 10:45
@andris-sevcenko Can we do that later today? Starting lunch in a minute :)

**Comment by andris-sevcenko** [comment] 2019-03-01 10:46
@nilsenpaul just don't forget :)

**Comment by lenvanessen** [comment] 2019-03-25 09:53
@andris-sevcenko this doesn't work. For some reason mollie webhooks don't work with the redirect that the endpoint gives. 

The url for customer returns should be different from the url for the webhook. The customer return url should have the redirect to the order page, but the webhook should simply look-up the payment and process is, if mollie encounters a redirect they simply abort the call it seems

**Comment by andris-sevcenko** [comment] 2019-03-25 10:14
@lenvanessen that sounds like a different issue. Can you open a new issue with detailed steps on how to reproduce?
